### ISSUE TITLE
Creating multiple primary level forward lookup zones

### ISSUE THREAD

**Issue by bigSOB** [EnclaveConsulting/SANS-SEC505#3]
I've run the script with the test txt file and it created all of the FLZ's outside of the created 000-Sinkhole FLZ. Is this a permissions issue or something with the script? I'd appreciate any assistance.
Thanks

**Comment by JasonFossen** [comment]
Hello, I'm not sure what you mean.  Did you get an error message?  If you sinkhole 1000 domains, for example, all 1000 are visible in the DNS snap-in (they are cached in memory), but they all share the one zone file on the drive.

**Comment by bigSOB** [comment]
You’re correct, I’m seeing them all as seperate forward lookup zones in the
snapin. I realize now they are all managed by the primary one your script
creates and the more I think about it, you cant put a domain under another
domains flz because the fqdn will get appended and it wont work. I just
wasn’t thinking it through and was surprised when I saw all the FLZ’s
appear that I wasn’t expecting.
Great script, and sorry for being a little bone headed on a Friday.
Thanks for following up,
Sean

**Comment by bigSOB** [comment]
Jason,
We've run into an issue, and I was hoping you might point me in the right
direction. We had a few sinkhole DNS records that were deleted manually,
instead of using the sinkhole_DNS.ps1 -DeleteSinkHoleDomains command (b/c
we didnt want to delete them all), and they no longer show up as DNS
records on our windows server. However, when we do nslookup's for those
domains, they point at our sinkhole IP address and one of them is blocking
mail delivery to anything yahoo. Any advice on dealing with ghost/orphaned
DNS records on Windows 2016? I'm really unsure of where they are being
stored and reported form, we went through all of our zones with a fine
toothed comb and found nothing.
Thoughts or advice would be greatly appreciated.
Sean

**Comment by JasonFossen** [comment]
Hi Sean:
Yah, the script is not really designed for that.  If there are names you don't want to sinkhole, they should be removed from the input file and then rerun the script. The reason is that sinkholed names are cached in the memory of the DNS server.  On the clients, remember that clients cache responses to prior queries for a time too.  To get back to square one, you can rerun the script to delete all sinkholed names and then update the input file to remove the names you don't want to sinkhole.  (Also, if you've experimented with the other sinkholing script which only modifies hosts files, then any modified hosts files would need to be edited too.) 
Hope this helps!
   Cheers, J.
